#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

cleanContacts() {
   cd "${XDG_DATA_HOME:-$HOME/.local/share}/contacts/contacts"
   sed -i 's/;VALUE=uri:tel//g' *
}

blog() {
cd ~/projects/joshmuller.ca
hugo new -k blog content/writings/2022/$1.md
vim content/writings/2022/$1.md
}

mp4comp() {
	ffmpeg -i "$1" -vcodec libx265 -crf 22 -vf scale=1280:720 "$1.compressed.mp4"
}

normmp4() {
   ffmpeg-normalize "$1" -o "normalized_$1" -c:a aac -b:a 192k
}

screen-record-compress() {
   ffmpeg -i "$1" -fs 90M $2
   normmp4 $2
}

awbry() {
   youtube-dl --get-filename -o "\"%(title)s.%(ext)s\"" "https://lbry.tv/$1" | xclip -sel c
}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
   whereismyphone="brave 'https://www.google.com/search?q=where+is+my+phone&btnK=Google+Search'" \
   waha="brave https://bible.com/bible/170/JHN.9 & audacity & " \
   mine="sudo xmrig -o us-west.minexmr.com:443 -u 86YtaybNw9RiW6jURyaaDFNBKhmiESYjk6XqZX8hrysoUNb3kujStQBeJM2CaYjGsNFHnvFHEhx2TQHgExYmj8p9G1cNH5w -k --tls  --randomx-1gb-pages -t 1" \
   mine-full="sudo xmrig -o us-west.minexmr.com:443 -u 86YtaybNw9RiW6jURyaaDFNBKhmiESYjk6XqZX8hrysoUNb3kujStQBeJM2CaYjGsNFHnvFHEhx2TQHgExYmj8p9G1cNH5w -k --tls  --randomx-1gb-pages -t 4" \
   mine-half="sudo xmrig -o us-west.minexmr.com:443 -u 86YtaybNw9RiW6jURyaaDFNBKhmiESYjk6XqZX8hrysoUNb3kujStQBeJM2CaYjGsNFHnvFHEhx2TQHgExYmj8p9G1cNH5w -k --tls  --randomx-1gb-pages -t 2" \
   nf="vim j.bb && rm j.bb" \
   mpv360="mpv --ytdl-format=\"bestvideo[height<=?360]+bestaudio/best\" " \
   m360="mpv --ytdl-format=\"bestvideo[height<=?360]+bestaudio/best\" " \
	mkd="mkdir -pv" \
	yt="yt-dlp --add-metadata -f 'bestvideo[height<=?720]+bestaudio/best[height<=?720]' -i" \
	yts="tsp yt-dlp --add-metadata -f 'bestvideo[height<=?720]+bestaudio/best[height<=?720]' -i" \
	yt360="yt-dlp --add-metadata -f 'bestvideo[height<=?360]+bestaudio/best[height<=?360]' -i" \
	yta="yt -x --audio-format mp3" \
	ffmpeg="ffmpeg -hide_banner" \
	ka="killall" \
	g="git" \
	k="khard" \
	b="khard -c $HOME/.config/khard/bcc.conf " \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura" \
	firefox="firefox --profile ~/.local/share/mozilla" \
	urls="$EDITOR $HOME/.config/newsboat/urls" \
	wn="mpv $HOME/.local/share/WhiteNoise.mp3 --loop=inf" \

alias \
	magit="$EDITOR -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
	school="$EDITOR ~/w/gtd/projects/school_guz_2020-2021/main.md" \
	faq="$EDITOR ~/w/gtd/reference/FAQ\ \&\ Standard\ Messages.md" \
	n="$EDITOR $INBOX_DOC" \
	j="cd ~/w/journal/ && touch $(date '+%Y-%m-%d.md') && git add $(date '+%Y-%m-%d.md') && $EDITOR $(date '+%Y-%m-%d.md')  " \
	emoji="$EDITOR ~/.local/share/larbs/emoji" \
	awb="youtube-dl --playlist-reverse \"https://m.youtube.com/c/AlephwithBeth/\" -f 'bestvideo[height<=?720]+bestaudio/best[height<=?720]' --download-archive ${XDG_CONFIG_HOME:-$HOME/.config}/youtube-dl/archive --output '$HOME/in/AwB/%(playlist_index)s-%(title)s.%(ext)s'" \
	gcd="git commit -a -m \"$(date -I)\"" \
	cite="$EDITOR $DOCS/reference/citations.bib" \
	cleanwa="rm paper.aux paper.b* paper.log paper.out paper.pdf paper.run.xml paper.txt" \
	wa="pdflatex paper.tex && biber paper && pdflatex paper.tex && pdftotext paper.pdf && zathura paper.pdf" \
